version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - cloudName=${cloudName}
      - apiKey=${apiKey}
      - apiSecret=${apiSecret}
      - DbUrl=${DbUrl}
      - DbName=${DbName}
      - DbPassword=${DbPassword}

    restart: always
